# Generated by Django 2.2.7 on 2019-11-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(db_index=True, max_length=4, verbose_name='Age')),
                ('location', models.CharField(db_index=True, max_length=12, verbose_name='Location')),
                ('specialty', models.CharField(db_index=True, max_length=15, verbose_name='Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='blog', verbose_name='Image')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Title')),
                ('body', models.TextField(max_length=5000, verbose_name='Body')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_logo', models.ImageField(blank=True, default='', upload_to='client_logo', verbose_name='Client Logo')),
                ('client_url', models.CharField(db_index=True, max_length=30, verbose_name='Client Url')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='Phone')),
                ('mail', models.CharField(db_index=True, max_length=30, verbose_name='Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, max_length=16, verbose_name='Education Year')),
                ('schooll', models.CharField(db_index=True, max_length=50, verbose_name='School/University')),
                ('location', models.CharField(db_index=True, max_length=30, verbose_name='Education Location')),
                ('body', models.TextField(max_length=1000, verbose_name='Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1', models.CharField(db_index=True, max_length=12, verbose_name='')),
                ('option_2', models.CharField(db_index=True, max_length=12, verbose_name='')),
                ('option_3', models.CharField(db_index=True, max_length=12, verbose_name='')),
                ('body', models.TextField(max_length=3000, verbose_name='Experience Body')),
            ],
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(db_index=True, max_length=6, verbose_name='Fact Cunt')),
                ('fact', models.CharField(db_index=True, max_length=20, verbose_name='Fact')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20, verbose_name='Pricing Plain')),
                ('price', models.CharField(db_index=True, max_length=6, verbose_name='Price')),
                ('option_1', models.CharField(db_index=True, max_length=20, verbose_name='Option')),
                ('option_2', models.CharField(db_index=True, max_length=20, verbose_name='Option')),
                ('option_3', models.CharField(db_index=True, max_length=20, verbose_name='Option')),
                ('option_4', models.CharField(db_index=True, max_length=20, verbose_name='Option')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='pdf', verbose_name='Resume File')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Service Name')),
                ('body', models.TextField(max_length=2000, verbose_name='Service Characteristics')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(db_index=True, max_length=60, verbose_name='Skills')),
                ('skill_level', models.CharField(db_index=True, max_length=3, verbose_name='Skill level')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExprerience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, max_length=16, verbose_name='Exprerience Year')),
                ('schooll', models.CharField(db_index=True, max_length=50, verbose_name='Specialty')),
                ('location', models.CharField(db_index=True, max_length=50, verbose_name='Exprerience Location')),
                ('body', models.TextField(max_length=1000, verbose_name='Job Description')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works', verbose_name='Work Image')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Work Name')),
                ('work_url', models.CharField(db_index=True, max_length=50, verbose_name='Work Url')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Category')),
            ],
        ),
    ]
