# Generated by Django 2.2.7 on 2019-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'Abaut Me'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experience'},
        ),
        migrations.AlterModelOptions(
            name='facts',
            options={'verbose_name': 'Fact', 'verbose_name_plural': 'Facts'},
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name': 'Pricing', 'verbose_name_plural': 'Pricing'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resume'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='workexprerience',
            options={'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experience'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_level',
            field=models.CharField(db_index=True, max_length=3, verbose_name='Skill Level'),
        ),
    ]
