# Generated by Django 2.2.7 on 2019-11-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191128_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='body',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Body'),
        ),
    ]
