# Generated by Django 2.2.7 on 2019-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutme_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='introduction',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Introduction'),
        ),
    ]
