# Generated by Django 2.2.7 on 2019-11-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Telegram'),
        ),
    ]
