# Generated by Django 2.2.7 on 2019-11-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Location'),
        ),
    ]
