# Generated by Django 2.2.7 on 2019-11-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexprerience',
            old_name='schooll',
            new_name='specialty',
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='location',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='specialty',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Specialty'),
        ),
    ]
