# Generated by Django 2.2.7 on 2019-11-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191128_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Full Name')),
                ('speciality', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Speciality')),
                ('fb', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Facebook')),
                ('lin', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='LinkedIn')),
                ('gt', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='GitHub')),
                ('tm', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Telegram')),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='option_1',
            field=models.CharField(db_index=True, max_length=30, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='option_2',
            field=models.CharField(db_index=True, max_length=30, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='option_3',
            field=models.CharField(db_index=True, max_length=30, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='workexprerience',
            name='year',
            field=models.CharField(db_index=True, max_length=25, verbose_name='Exprerience Year'),
        ),
    ]
