# Generated by Django 2.2.7 on 2019-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191128_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.RemoveField(
            model_name='facts',
            name='count',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='fact',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='body',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
        migrations.AddField(
            model_name='facts',
            name='count_1',
            field=models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Fact Cunt'),
        ),
        migrations.AddField(
            model_name='facts',
            name='count_2',
            field=models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Fact Cunt'),
        ),
        migrations.AddField(
            model_name='facts',
            name='count_3',
            field=models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Fact Cunt'),
        ),
        migrations.AddField(
            model_name='facts',
            name='count_4',
            field=models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Fact Cunt'),
        ),
        migrations.AddField(
            model_name='facts',
            name='fact_1',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Fact'),
        ),
        migrations.AddField(
            model_name='facts',
            name='fact_2',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Fact'),
        ),
        migrations.AddField(
            model_name='facts',
            name='fact_3',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Fact'),
        ),
        migrations.AddField(
            model_name='facts',
            name='fact_4',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Fact'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_c_1',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_c_2',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_c_3',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_c_4',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_l_1',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_l_2',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_l_3',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_l_4',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_r_1',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_r_2',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_r_3',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='option_r_4',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='price_c',
            field=models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='price_l',
            field=models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='price_r',
            field=models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='title_c',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Pricing Plain'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='title_l',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Pricing Plain'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='title_r',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Pricing Plain'),
        ),
        migrations.AddField(
            model_name='services',
            name='body_1',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Service Characteristics'),
        ),
        migrations.AddField(
            model_name='services',
            name='body_2',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Service Characteristics'),
        ),
        migrations.AddField(
            model_name='services',
            name='body_3',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Service Characteristics'),
        ),
        migrations.AddField(
            model_name='services',
            name='body_4',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Service Characteristics'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_1',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_2',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_3',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_4',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Service Name'),
        ),
    ]
