# Generated by Django 2.2.7 on 2019-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191130_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Telegram Name'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_logo',
            field=models.ImageField(default='', upload_to='client_logo/', verbose_name='Client Logo'),
        ),
    ]
