# Generated by Django 2.2.7 on 2019-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191202_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_level',
            field=models.CharField(db_index=True, max_length=3, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='works',
            name='image',
            field=models.ImageField(upload_to='works/', verbose_name='Work Image'),
        ),
        migrations.AlterField(
            model_name='works',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Work Name'),
        ),
        migrations.AlterField(
            model_name='works',
            name='work_url',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Work Url'),
        ),
    ]
