# Generated by Django 2.2.7 on 2019-12-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191205_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AddField(
            model_name='about',
            name='cv',
            field=models.FileField(blank=True, upload_to='pdf', verbose_name='CV File'),
        ),
    ]
